name: Publish Release

on:
  workflow_dispatch:

jobs:
  publish:
    uses: credibil/pipeline/.github/workflows/publish.yaml@main

  crates:
    needs: publish
    uses: credibil/pipeline/.github/workflows/crates.yaml@main
    secrets: inherit